"""empty message

Revision ID: c68218608645
Revises: 3f691fa00711
Create Date: 2023-09-26 21:13:34.507732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68218608645'
down_revision = '3f691fa00711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brief', sa.String(length=3), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('code', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_brief'), 'fund', ['brief'], unique=True)
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brief', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('fund_id', sa.Integer(), nullable=True),
    sa.Column('dateStart', sa.DateTime(), nullable=True),
    sa.Column('dateEnd', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['fund.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_brief'), 'resource', ['brief'], unique=True)
    op.create_index(op.f('ix_resource_dateEnd'), 'resource', ['dateEnd'], unique=False)
    op.create_index(op.f('ix_resource_dateStart'), 'resource', ['dateStart'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_dateStart'), table_name='resource')
    op.drop_index(op.f('ix_resource_dateEnd'), table_name='resource')
    op.drop_index(op.f('ix_resource_brief'), table_name='resource')
    op.drop_table('resource')
    op.drop_index(op.f('ix_fund_brief'), table_name='fund')
    op.drop_table('fund')
    # ### end Alembic commands ###
